### ISSUE TITLE
Binding a class using an async pipe

### ISSUE THREAD

**Issue by xxgreg** [dart-lang/angular2#162]
Should the following work in a template?

```
[class.done]="done | async"
```

I'm getting angry messages in the console. At a quick glance it looks like null is being passed to `AppView.updateClass()` instead of a bool.

Happy to add more information if it is helpful.

**Comment by xxgreg** [comment]
In this example I expect that bar class would be toggled every 500ms.

```
@Component(
  selector: 'foo',
  template: r'''
  <div [class.bar]="bar | async"></div>
  ''',
)
class Foo {
  Stream<bool> bar = new Stream.periodic(
      new Duration(milliseconds: 500), (t) => t % 2 == 0);
}
```

But I get the following stacktrace instead:
```
#0      AppView.updateClass (package:angular2/src/core/linker/app_view.dart:378:9)
#1      _View_Foo0.detectChangesInternal (package:mvw_todo/app_component.template.dart:151:7)
#2      AppView.detectChanges (package:angular2/src/core/linker/app_view.dart:269:10)
#3      DebugAppView.detectChanges (package:angular2/src/debug/debug_app_view.dart:91:28)
#4      AppView.detectViewChildrenChanges (package:angular2/src/core/linker/app_view.dart:293:23)
#5      AppView.detectChangesInternal (package:angular2/src/core/linker/app_view.dart:280:10)
#6      AppView.detectChanges (package:angular2/src/core/linker/app_view.dart:269:10)
#7      DebugAppView.detectChanges (package:angular2/src/debug/debug_app_view.dart:91:28)
#8      AppView.detectViewChildrenChanges (package:angular2/src/core/linker/app_view.dart:293:23)
#9      AppView.detectChangesInternal (package:angular2/src/core/linker/app_view.dart:280:10)
#10     AppView.detectChanges (package:angular2/src/core/linker/app_view.dart:269:10)
#11     DebugAppView.detectChanges (package:angular2/src/debug/debug_app_view.dart:91:28)
#12     ViewRef_.detectChanges (package:angular2/src/core/linker/view_ref.dart:99:11)
#13     ApplicationRefImpl.tick (package:angular2/src/core/application_ref.dart:403:32)
#14     ApplicationRefImpl._loadComponent (package:angular2/src/core/application_ref.dart:373:5)
#15     ApplicationRefImpl.bootstrap.<anonymous closure> (package:angular2/src/core/application_ref.dart:358:7)
#16     ApplicationRefImpl.run.<anonymous closure> (package:angular2/src/core/application_ref.dart:318:26)
#17     _rootRun (dart:async/zone.dart:1146)
#18     _ZoneDelegate.run (dart:async/zone.dart:693)
#19     NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:155:21)
#20     _CustomZone.run (dart:async/zone.dart:1026)
#21     NgZoneImpl.runInner (package:angular2/src/core/zone/ng_zone_impl.dart:126:23)
#22     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:220:27)
#23     ApplicationRefImpl.run (package:angular2/src/core/application_ref.dart:316:10)
#24     ApplicationRefImpl.bootstrap (package:angular2/src/core/application_ref.dart:345:12)
#25     coreLoadAndBootstrap.<coreLoadAndBootstrap_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:angular2/src/core/application_ref.dart:99:19)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#27     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135:26)
#28     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#29     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135:14)
#30     NgZoneImpl._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone_impl.dart:162:40)
#31     _rootRun (dart:async/zone.dart:1146)
#32     _ZoneDelegate.run (dart:async/zone.dart:693)
#33     NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:155:21)
#34     NgZoneImpl._runUnary (package:angular2/src/core/zone/ng_zone_impl.dart:162:7)
#35     _CustomZone.runUnary (dart:async/zone.dart:1037)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#37     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#38     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#39     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#42     _ScheduleImmediateHelper._handleMutation (dart:html:49308)
```

**Comment by matanlurey** [comment]
I'd recommend not using Pipes if you strictly require a boolean expression - `async` pipe returns `null` until the first event on the `Future` or `Stream`.

Let me know if you can just use `async` / `await`.

We might be able to improve this in the future.

**Comment by zoechi** [comment]
`[class.done]="(done | async) ?? false"` might work then
