### ISSUE TITLE
Unable to update *ngFor attribute used for ngControl

### ISSUE THREAD

**Issue by Adamovskiy** [dart-lang/angular2#164]
Updating `*ngFor` list argument when its index is used to generate `ngControl` value causes exception, in Dartium:
```
EXCEPTION: The null object does not have a method 'updateValue'.

NoSuchMethodError: method not found: 'updateValue'
Receiver: null
Arguments: ["true"]
VM700:1 EXCEPTION: The null object does not have a method 'updateValue'.

NoSuchMethodError: method not found: 'updateValue'
Receiver: null
Arguments: ["true"](anonymous function) @ VM700:1
VM700:1 STACKTRACE:(anonymous function) @ VM700:1
VM700:1 #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      NgForm.updateModel.<anonymous closure> (package:angular2/src/common/forms/directives/ng_form.dart:167:12)
#3      _rootRun (dart:async/zone.dart:1146)
#4      _ZoneDelegate.run (dart:async/zone.dart:693)
#5      NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:146:21)
#6      _CustomZone.run (dart:async/zone.dart:1026)
#7      _CustomZone.runGuarded (dart:async/zone.dart:924)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#9      NgZoneImpl._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone_impl.dart:167:11)
#10     _rootRun (dart:async/zone.dart:1150)
#11     _ZoneDelegate.run (dart:async/zone.dart:693)
#12     NgZoneImpl._run (package:angular2/src/core/zone/ng_zone_impl.dart:146:21)
#13     _CustomZone.run (dart:async/zone.dart:1026)
#14     _CustomZone.runGuarded (dart:async/zone.dart:924)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _ScheduleImmediateHelper._handleMutation (dart:html:49308)
```
in Chrome:
```
EXCEPTION: NullError: method not found: 'updateValue$1' on null
html_dart2js.dart:3352 EXCEPTION: NullError: method not found: 'updateValue$1' on nulllogGroup$1 @ html_dart2js.dart:3352(anonymous function) @ exception_handler.dart:57dart.ExceptionHandler.call$3 @ exception_handler.dart:84dart.ApplicationRefImpl_closure1.call$1 @ application_ref.dart:263dart._rootRunUnary @ zone.dart:1162runUnaryGuarded$2 @ zone.dart:1340_sendData$1 @ stream_impl.dart:331dart._BufferingStreamSubscription._async$_add$1 @ stream_impl.dart:258_sendData$1 @ broadcast_stream_controller.dart:386call$1 @ broadcast_stream_controller.dart:261dart.NgZoneImpl._onErrorWithoutLongStackTrace$5 @ ng_zone_impl.dart:187(anonymous function) @ VM116:2dart._CustomZone.handleUncaughtError$2 @ zone.dart:1005runGuarded$1 @ zone.dart:926dart._CustomZone_bindCallback_closure.call$0 @ zone.dart:951dart.NgZoneImpl__scheduleMicrotask_closure.call$0 @ ng_zone_impl.dart:167dart._rootRun @ zone.dart:1150dart._ZoneDelegate.run$2 @ zone.dart:693dart.NgZoneImpl._run$4 @ ng_zone_impl.dart:146(anonymous function) @ VM120:2dart._CustomZone.run$1 @ zone.dart:1026runGuarded$1 @ zone.dart:924dart._CustomZone_bindCallback_closure.call$0 @ zone.dart:951_microtaskLoop @ schedule_microtask.dart:41dart._startMicrotaskLoop @ schedule_microtask.dart:50dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1 @ async_patch.dart:54call$0 @ js_helper.dart:2409eval$1 @ isolate_helper.dart:462_callInIsolate @ isolate_helper.dart:54dart.invokeClosure @ js_helper.dart:2409(anonymous function) @ js_helper.dart:2429
html_dart2js.dart:3352 STACKTRACE:logError$1 @ html_dart2js.dart:3352(anonymous function) @ exception_handler.dart:61dart.ExceptionHandler.call$3 @ exception_handler.dart:84dart.ApplicationRefImpl_closure1.call$1 @ application_ref.dart:263dart._rootRunUnary @ zone.dart:1162runUnaryGuarded$2 @ zone.dart:1340_sendData$1 @ stream_impl.dart:331dart._BufferingStreamSubscription._async$_add$1 @ stream_impl.dart:258_sendData$1 @ broadcast_stream_controller.dart:386call$1 @ broadcast_stream_controller.dart:261dart.NgZoneImpl._onErrorWithoutLongStackTrace$5 @ ng_zone_impl.dart:187(anonymous function) @ VM116:2dart._CustomZone.handleUncaughtError$2 @ zone.dart:1005runGuarded$1 @ zone.dart:926dart._CustomZone_bindCallback_closure.call$0 @ zone.dart:951dart.NgZoneImpl__scheduleMicrotask_closure.call$0 @ ng_zone_impl.dart:167dart._rootRun @ zone.dart:1150dart._ZoneDelegate.run$2 @ zone.dart:693dart.NgZoneImpl._run$4 @ ng_zone_impl.dart:146(anonymous function) @ VM120:2dart._CustomZone.run$1 @ zone.dart:1026runGuarded$1 @ zone.dart:924dart._CustomZone_bindCallback_closure.call$0 @ zone.dart:951_microtaskLoop @ schedule_microtask.dart:41dart._startMicrotaskLoop @ schedule_microtask.dart:50dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1 @ async_patch.dart:54call$0 @ js_helper.dart:2409eval$1 @ isolate_helper.dart:462_callInIsolate @ isolate_helper.dart:54dart.invokeClosure @ js_helper.dart:2409(anonymous function) @ js_helper.dart:2429
html_dart2js.dart:3352 TypeError: Cannot read property 'updateValue$1' of null
    at NgForm_updateModel_closure.dart.NgForm_updateModel_closure.call$0 (model.dart:200)
    at StaticClosure.dart._rootRun (zone.dart:1146)
    at _ZoneDelegate.dart._ZoneDelegate.run$2 (zone.dart:693)
    at NgZoneImpl.dart.NgZoneImpl._run$4 (ng_zone_impl.dart:146)
    at Object.eval (eval at Closure_forwardCallTo (js_helper.dart:2748), <anonymous>:2:45)
    at _CustomZone.dart._CustomZone.run$1 (zone.dart:1026)
    at _CustomZone.runGuarded$1 (zone.dart:924)
    at _CustomZone_bindCallback_closure.dart._CustomZone_bindCallback_closure.call$0 (zone.dart:951)
    at NgZoneImpl__scheduleMicrotask_closure.dart.NgZoneImpl__scheduleMicrotask_closure.call$0 (ng_zone_impl.dart:167)
    at StaticClosure.dart._rootRun (zone.dart:1150)
```
 Code sample:
```dart
@Component(
    selector: 'my-app',
    template: '''
<form>
    <input *ngFor="let val of vals; let idx = index" [ngModel]="val" ngControl="input-{{idx}}">
</form>
''')
class AppComponent {
  Iterable<String> vals;
  bool b = false;

  void _update() {
    vals = new List.from([b.toString()]);
    b = !b;
  }

  AppComponent() {
    _update();
    new Timer.periodic(const Duration(seconds:1), (Timer t) => _update());
  }
}
```
Angular version `2.0.0` (in `2.0.0-beta.17` it was ok).

**Comment by bunopus** [comment]
+1

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce as stated in the issue template.

**Comment by Adamovskiy** [comment]
https://github.com/Adamovskiy/ngfor-ngcontrol-bug

**Comment by zoechi** [comment]
What about a Plunker?

**Comment by Adamovskiy** [comment]
@zoechi but Plunker does not support dart-angular2, or am I wrong? At least, there is no such option in "New" menu.

**Comment by zoechi** [comment]
Ouch, sorry. Missed that this is in the Dart repo. I'm also following the TS issues. Sorry for the noise.

**Comment by matanlurey** [comment]
Sorry for the delay. Investigating.

**Comment by matanlurey** [comment]
Great, reproduced. Fix is out for next release.
