### ISSUE TITLE
IE11 Routing Bug

### ISSUE THREAD

**Issue by dergemkr** [dart-lang/angular2#94]
Routing seems to be broken in IE11.  It reports the following error:

```
EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: RangeError (index): Index out of range: no indices are valid: 0
ORIGINAL STACKTRACE:
RangeError (index): Index out of range: no indices are valid: 0
   at ioore (http://localhost:8080/main.dart.js:2889:7)
   at BrowserDomAdapter.getBaseHref$0 (http://localhost:8080/main.dart.js:17859:11)
   at BrowserPlatformLocation.getBaseHrefFromDOM$0 (http://localhost:8080/main.dart.js:17922:9)
   at PathLocationStrategy.PathLocationStrategy$2 (http://localhost:8080/main.dart.js:18200:11)
   at PathLocationStrategy.static.PathLocationStrategy$ (http://localhost:8080/main.dart.js:18208:11)
   at _View_AppComponent_Host0.get$_LocationStrategy_0_8 (http://localhost:8080/main.dart.js:22021:11)
   at _View_AppComponent_Host0.get$_Location_0_9 (http://localhost:8080/main.dart.js:22030:11)
   at _View_AppComponent_Host0.injectorGetInternal$3 (http://localhost:8080/main.dart.js:22083:13)
   at Anonymous function (http://localhost:8080/main.dart.js:16169:9)
   at DebugAppView.injectorGet$3 (http://localhost:8080/main.dart.js:17473:11)
ERROR CONTEXT:
Instance of 'DebugContext'
   {
      [functions]: ,
      $builtinTypeInfo: [ ],
      ^: "Object;_debug_context$_view,_debug_context$_nodeIndex,_tplRow,_tplCol",
      __proto__: { },
      _debug_context$_nodeIndex: 0,
      _debug_context$_view: { },
      _tplCol: 0,
      _tplRow: 0
   }

```

To reproduce, clone [this ](https://github.com/dergemkr/ie11-dart-angular2-bug-example) example and load it in IE11. The error occurs on page load.

Though, I have not been able to find documentation on what browsers Angular 2 Dart supports. Is IE11 is not supported?

**Comment by enyo** [comment]
I also just ran into this problem. @dergemkr have you found a way around it?
Unfortunately, no IE11 support is a big deal, since it's still pretty widely used.

**Comment by DanielTal** [comment]
likewise , posted similar issue here
https://github.com/angular-examples/toh-6/issues/3

**Comment by dergemkr** [comment]
@enyo - It seems to go away if you use a `<base href>` other than `/`.  (i.e. Moving everything into a sub directory setting `<base href="/sub/">`)

**Comment by enyo** [comment]
@dergemkr You are right! Wow, that is an unexpected error

**Comment by DanielTal** [comment]
@dergemkr 
many many thanks for this golden tip!
It solved our problem with IE11.
And it explains why the toh6 tutorial demo worked in the live example 
and not when we hosted in the root domain of our server.

**Comment by enyo** [comment]
Mh... but that means that the website needs to always run in a subfolder... That's less than ideal

**Comment by matanlurey** [comment]
Fix is out internally, I'll sync up as soon as I can.

**Comment by enyo** [comment]
Thanks @matanlurey! I also updated the [stackoverflow issue](http://stackoverflow.com/questions/40960760/how-to-get-angular2-dart-to-work-in-ie11/40999803#40999803)
